// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5247.TestDrive.subsystems;


import org.usfirst.frc5247.TestDrive.RobotMap;
import org.usfirst.frc5247.TestDrive.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS



//Open/close claw. Forks in/out.
public class ClawHorizontal extends Subsystem {
   private static Talon claw = new Talon(RobotMap.clawHorizontal);

    public ClawHorizontal() {
       //claw = new Talon(RobotMap.clawHorizontal);
        
    }
    public void clawLeft() {
        //claw.set(.5);
    }
    public void clawRight() {
        //claw.set(-.5);
    }
    public  void Stop() {
        //claw.set(0);
    }
    @Override
    public void initDefaultCommand() {
      //  setDefaultCommand(new ClawUp());
       // setDefaultCommand(new ClawDown());

    }

    @Override
    public void periodic() {
       
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

